const foodDatabase = [
  //vegetables
  {
    id: 0,
    name: "lechuga",
    type: "vegetables",
    weight_int: 150,
    prot: 2.1,
    lip: 0.6,
    hc: 2.6,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/vegetables/lettuce.png",
  },

  {
    id: 1,
    name: "tomate",
    type: "vegetables",
    weight_int: 150,
    prot: 1.4,
    lip: 0.2,
    hc: 5.3,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/vegetables/rsz_tomato.png",
  },
  {
    id: 2,
    name: "zanahoria",
    type: "vegetables",
    weight_int: 100,
    prot: 0.8,
    lip: 0.3,
    hc: 7,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/vegetables/carrot.png",
  },
  {
    id: 3,
    name: "brocoli",
    type: "vegetables",
    weight_int: 150,
    prot: 4.5,
    lip: 0.6,
    hc: 3.6,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/vegetables/broccoli_8.png",
  },
  //starchyFoods
  {
    id: 4,
    name: "avena",
    type: "starchyFoods",
    weight_int: 20,
    prot: 2.7,
    lip: 1.4,
    hc: 11.8,
    n_int_card: 0,
    img_link: "./assets/images_date_basesAlimentos/starchyFoods/oats.png",
  },
  {
    id: 5,
    name: "arroz",
    type: "starchyFoods",
    weight_int: 20,
    prot: 1.4,
    lip: 0.2,
    hc: 15.2,
    n_int_card: 0,
    img_link: "./assets/images_date_basesAlimentos/starchyFoods/rice_whole.png",
  },
  {
    id: 6,
    name: "patatas",
    type: "starchyFoods",
    weight_int: 100,
    prot: 2.2,
    lip: 0.2,
    hc: 15.2,
    n_int_card: 0,
    img_link:
      "./assets/images_date_basesAlimentos/starchyFoods/potato_2147541_640.png",
  },
  {
    id: 7,
    name: "lentejas",
    type: "starchyFoods",
    weight_int: 30,
    prot: 7.3,
    lip: 0.4,
    hc: 14.6,
    n_int_card: 0,
    img_link: "./assets/images_date_basesAlimentos/starchyFoods/lentils.png",
  },
  //proteinFoods
  {
    id: 8,
    name: "tofu",
    type: "proteinFoods",
    weight_int: 45,
    prot: 7.2,
    lip: 3.6,
    hc: 0.225,
    n_int_card: 0,
    img_link: "./assets/images_date_basesAlimentos/proteinFoods/tofu.png",
  },
  //nuts
  {
    id: 9,
    name: "almendras",
    type: "nuts",
    weight_int: 8,
    prot: 1.5,
    lip: 4.3,
    hc: 0.5,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/nuts/almond_PNG38.png",
  },
  {
    id: 10,
    name: "pipas",
    type: "nuts",
    weight_int: 8,
    prot: 1.84,
    lip: 3.92,
    hc: 0.96,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/nuts/seeds_pumpkin.png",
  },
  //fats
  {
    id: 11,
    name: "aceite",
    type: "fats",
    weight_int: 5,
    prot: 0,
    lip: 5,
    hc: 0,
    n_int_card: 0,
    img_link: "./assets/images_date_basesAlimentos/fats/oil .png",
  },
  {
    id: 12,
    name: "plátano",
    type: "fruits",
    weight_int: 80,
    prot: 0.9,
    lip: 0.2,
    hc: 16.9,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/fruits/banana_PNG842.png",
  },
  {
    id: 13,
    name: "naranja",
    type: "fruits",
    weight_int: 200,
    prot: 2,
    lip: 0.2,
    hc: 16.4,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/fruits/orange.png",
  },
  {
    id: 14,
    name: "manzana",
    type: "fruits",
    weight_int: 120,
    prot: 0.4,
    lip: 0.4,
    hc: 14,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/fruits/apple_K.png",
  },

  {
    id: 15,
    name: "leche",
    type: "dairyProducts",
    weight_int: 250,
    prot: 7.8,
    lip: 4.3,
    hc: 1.5,
    n_int_card: 1,
    img_link: "./assets/images_date_basesAlimentos/dairyProducts/soy_milk.png",
  },
];

export default foodDatabase;
